name: "They need love"
services:
  db:
    container_name: "db"
    image: "postgres"
    restart: "always"
    # set shared memory limit when using docker-compose
    shm_size: "128mb"
    environment:
      POSTGRES_PASSWORD: "example"
    ports:
      - "5432:5432"
